from scipy._typing import Untyped

PyCFuncPtr: Untyped
ffi: Untyped

class CData: ...

class LowLevelCallable(tuple):
    def __new__(cls, function, user_data: Untyped | None = None, signature: Untyped | None = None) -> Untyped: ...
    @property
    def function(self) -> Untyped: ...
    @property
    def user_data(self) -> Untyped: ...
    @property
    def signature(self) -> Untyped: ...
    def __getitem__(self, idx): ...
    @classmethod
    def from_cython(cls, module, name, user_data: Untyped | None = None, signature: Untyped | None = None) -> Untyped: ...
