from scipy._typing import Untyped

class DisjointSet:
    n_subsets: int
    def __init__(self, elements: Untyped | None = None): ...
    def __iter__(self) -> Untyped: ...
    def __len__(self) -> int: ...
    def __contains__(self, x) -> bool: ...
    def __getitem__(self, x) -> Untyped: ...
    def add(self, x): ...
    def merge(self, x, y) -> Untyped: ...
    def connected(self, x, y) -> Untyped: ...
    def subset(self, x) -> Untyped: ...
    def subset_size(self, x) -> Untyped: ...
    def subsets(self) -> Untyped: ...
