from collections.abc import Generator

from scipy._typing import Untyped

IS_PYPY: Untyped

class ReferenceError(AssertionError): ...

def set_gc_state(state): ...
def gc_state(state) -> Generator[None, None, None]: ...
def assert_deallocated(func, *args, **kwargs) -> Generator[Untyped, None, None]: ...
