from scipy._typing import Untyped

class ReentrancyError(RuntimeError): ...

class ReentrancyLock:
    def __init__(self, err_msg) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None): ...
    def decorate(self, func) -> Untyped: ...

def non_reentrant(err_msg: Untyped | None = None) -> Untyped: ...
