from contextlib import _GeneratorContextManager

from _typeshed import FileDescriptorOrPath

def tempdir() -> _GeneratorContextManager[str]: ...
def in_tempdir() -> _GeneratorContextManager[str]: ...
def in_dir(dir: FileDescriptorOrPath | None = None) -> _GeneratorContextManager[str]: ...
