from collections.abc import Generator

from scipy._typing import Untyped

def tempdir() -> Generator[Untyped, None, None]: ...
def in_tempdir() -> Generator[Untyped, None, None]: ...
def in_dir(dir: Untyped | None = None) -> Generator[Untyped, None, None]: ...
