from scipy._typing import Untyped

class _DeprecationHelperStr:
    def __init__(self, content, message) -> None: ...
    def __hash__(self) -> Untyped: ...
    def __eq__(self, other) -> Untyped: ...

def deprecate_cython_api(module, routine_name, new_name: Untyped | None = None, message: Untyped | None = None): ...
