from scipy._typing import Untyped

def docformat(docstring, docdict: Untyped | None = None) -> Untyped: ...
def inherit_docstring_from(cls) -> Untyped: ...
def extend_notes_in_docstring(cls, notes) -> Untyped: ...
def replace_notes_in_docstring(cls, notes) -> Untyped: ...
def indentcount_lines(lines) -> Untyped: ...
def filldoc(docdict, unindent_params: bool = True) -> Untyped: ...
def unindent_dict(docdict) -> Untyped: ...
def unindent_string(docstring) -> Untyped: ...
def doc_replace(obj, oldval, newval) -> Untyped: ...
