from scipy._typing import Untyped

def central_diff_weights(Np, ndiv: int = 1) -> Untyped: ...
def derivative(func, x0, dx: float = 1.0, n: int = 1, args=(), order: int = 3) -> Untyped: ...
def ascent() -> Untyped: ...
def face(gray: bool = False) -> Untyped: ...
def electrocardiogram() -> Untyped: ...
