from scipy import sparse as sparse
from scipy._lib._util import np_long as np_long, np_ulong as np_ulong
from scipy._typing import Untyped
from scipy.linalg import eig as eig, eigh as eigh, orth as orth, toeplitz as toeplitz
from scipy.sparse import csr_matrix as csr_matrix, diags as diags, eye as eye, spdiags as spdiags
from scipy.sparse.linalg import LinearOperator as LinearOperator, eigs as eigs
from scipy.sparse.linalg._eigen.lobpcg import lobpcg as lobpcg

INT_DTYPES: Untyped
REAL_DTYPES: Untyped
COMPLEX_DTYPES: Untyped
INEXECTDTYPES: Untyped
ALLDTYPES: Untyped

def sign_align(A, B) -> Untyped: ...
def ElasticRod(n) -> Untyped: ...
def MikotaPair(n) -> Untyped: ...
def compare_solutions(A, B, m): ...
def test_Small(): ...
def test_ElasticRod(): ...
def test_MikotaPair(): ...
def test_b_orthonormalize(n, m, Vdtype, Bdtype, BVdtype) -> Untyped: ...
def test_nonhermitian_warning(capsys): ...
def test_regression(): ...
def test_diagonal(n, m, m_excluded) -> Untyped: ...
def test_fiedler_small_8(): ...
def test_fiedler_large_12(): ...
def test_failure_to_run_iterations(): ...
def test_failure_to_run_iterations_nonsymmetric(): ...
def test_hermitian(): ...
def test_eigs_consistency(n, atol): ...
def test_verbosity(): ...
def test_tolerance_float32(): ...
def test_dtypes(vdtype, mdtype, arr_type): ...
def test_inplace_warning(): ...
def test_maxit(): ...
def test_diagonal_data_types(n, m) -> Untyped: ...
