from scipy.sparse._sputils import matrix as matrix

class TestSparseUtils:
    def test_upcast(self): ...
    def test_getdtype(self): ...
    def test_isscalarlike(self): ...
    def test_isintlike(self): ...
    def test_isshape(self): ...
    def test_issequence(self): ...
    def test_ismatrix(self): ...
    def test_isdense(self): ...
    def test_validateaxis(self): ...
    def test_get_index_dtype(self): ...
    def test_check_shape_overflow(self): ...
    def test_matrix(self): ...
    def test_asmatrix(self): ...
