from collections.abc import Generator

from scipy._typing import Untyped
from scipy.sparse import dok_array as dok_array, dok_matrix as dok_matrix

def d() -> Untyped: ...
def A() -> Untyped: ...
def Asp(request) -> Generator[Untyped, None, None]: ...
def test_dict_methods_covered(d, Asp): ...
def test_clear(d, Asp): ...
def test_copy(d, Asp): ...
def test_fromkeys_default(): ...
def test_fromkeys_positional(): ...
def test_fromkeys_iterator(): ...
def test_get(d, Asp): ...
def test_items(d, Asp): ...
def test_keys(d, Asp): ...
def test_pop(d, Asp): ...
def test_popitem(d, Asp): ...
def test_setdefault(d, Asp): ...
def test_update(d, Asp): ...
def test_values(d, Asp): ...
def test_dunder_getitem(d, Asp): ...
def test_dunder_setitem(d, Asp): ...
def test_dunder_delitem(d, Asp): ...
def test_dunder_contains(d, Asp): ...
def test_dunder_len(d, Asp): ...
def test_dunder_reversed(d, Asp): ...
def test_dunder_ior(d, Asp): ...
def test_dunder_or(d, Asp): ...
def test_dunder_ror(d, Asp): ...
def test_dunder_eq(A, Asp): ...
def test_dunder_ne(A, Asp): ...
def test_dunder_lt(A, Asp): ...
def test_dunder_gt(A, Asp): ...
def test_dunder_le(A, Asp): ...
def test_dunder_ge(A, Asp): ...
def test_dunder_iter(A, Asp): ...
