from scipy import sparse as sparse
from scipy.sparse import (
    csc_array as csc_array,
    csc_matrix as csc_matrix,
    csr_array as csr_array,
    csr_matrix as csr_matrix,
    hstack as hstack,
)

def test_csr_rowslice(): ...
def test_csr_getrow(): ...
def test_csr_getcol(): ...
def test_csr_empty_slices(matrix_input, axis, expected_shape): ...
def test_csr_bool_indexing(): ...
def test_csr_hstack_int64(): ...
def test_mixed_index_dtype_int_indexing(cls): ...
