from scipy._typing import Untyped
from scipy.sparse import csr_array as csr_array, csr_matrix as csr_matrix, sparray as sparray

class TestExtract:
    cases: Untyped
    def setup_method(self): ...
    def test_find(self): ...
    def test_tril(self): ...
    def test_triu(self): ...
    def test_array_vs_matrix(self): ...
