from scipy.sparse import coo_array as coo_array

def test_shape_constructor(): ...
def test_dense_constructor(): ...
def test_dense_constructor_with_shape(): ...
def test_dense_constructor_with_inconsistent_shape(): ...
def test_1d_sparse_constructor(): ...
def test_1d_tuple_constructor(): ...
def test_1d_tuple_constructor_with_shape(): ...
def test_non_subscriptability(): ...
def test_reshape(): ...
def test_nnz(): ...
def test_transpose(): ...
def test_transpose_with_axis(): ...
def test_1d_row_and_col(): ...
def test_1d_toformats(): ...
def test_1d_resize(arg: int): ...
def test_1d_to_2d_resize(arg: tuple[int, int]): ...
def test_2d_to_1d_resize(arg: int): ...
def test_sum_duplicates(): ...
def test_eliminate_zeros(): ...
def test_1d_add_dense(): ...
def test_1d_add_sparse(): ...
def test_1d_matmul_vector(): ...
def test_1d_matmul_multivector(): ...
def test_2d_matmul_multivector(): ...
def test_1d_diagonal(): ...
