from scipy._lib._testutils import check_free_memory as check_free_memory
from scipy._lib._util import check_random_state as check_random_state
from scipy._typing import Untyped
from scipy.sparse import (
    bsr_array as bsr_array,
    bsr_matrix as bsr_matrix,
    coo_array as coo_array,
    coo_matrix as coo_matrix,
    csc_array as csc_array,
    csc_matrix as csc_matrix,
    csr_array as csr_array,
    csr_matrix as csr_matrix,
    dia_array as dia_array,
    dia_matrix as dia_matrix,
    dok_array as dok_array,
    lil_array as lil_array,
    lil_matrix as lil_matrix,
    sparray as sparray,
    spmatrix as spmatrix,
)

sparse_formats: Untyped

class TestConstructUtils:
    def test_singleton_array_constructor(self, cls): ...
    def test_singleton_matrix_constructor(self, cls): ...
    def test_spdiags(self): ...
    def test_diags(self): ...
    def test_diags_default(self): ...
    def test_diags_default_bad(self): ...
    def test_diags_bad(self): ...
    def test_diags_vs_diag(self): ...
    def test_diags_dtype(self): ...
    def test_diags_one_diagonal(self): ...
    def test_diags_empty(self): ...
    def test_identity(self, identity): ...
    def test_eye(self, eye): ...
    def test_eye_one(self, eye): ...
    def test_eye_array_vs_matrix(self): ...
    def test_kron(self): ...
    def test_kron_ndim_exceptions(self): ...
    def test_kron_large(self): ...
    def test_kronsum(self): ...
    def test_kronsum_ndim_exceptions(self): ...
    def test_vstack(self, coo_cls): ...
    def test_vstack_matrix_or_array(self): ...
    def test_vstack_1d_with_2d(self): ...
    def test_hstack(self, coo_cls): ...
    def test_hstack_matrix_or_array(self): ...
    def test_block_creation(self, block_array): ...
    def test_block_return_type(self): ...
    def test_bmat_return_type(self): ...
    def test_concatenate_int32_overflow(self): ...
    def test_block_diag_basic(self): ...
    def test_block_diag_scalar_1d_args(self): ...
    def test_block_diag_1(self): ...
    def test_block_diag_sparse_arrays(self): ...
    def test_block_diag_return_type(self): ...
    def test_random_sampling(self) -> Untyped: ...
    def test_rand(self): ...
    def test_randn(self): ...
    def test_random_accept_str_dtype(self): ...
    def test_random_sparse_matrix_returns_correct_number_of_non_zero_elements(self): ...

def test_diags_array(): ...
