from scipy._lib._testutils import check_free_memory as check_free_memory
from scipy._typing import Untyped
from scipy.sparse import (
    bsr_matrix as bsr_matrix,
    coo_matrix as coo_matrix,
    csc_matrix as csc_matrix,
    csr_matrix as csr_matrix,
    dia_matrix as dia_matrix,
)
from scipy.sparse._sputils import supported_dtypes as supported_dtypes

def int_to_int8(n) -> Untyped: ...
def test_exception(): ...
def test_threads(): ...
def test_regression_std_vector_dtypes(): ...
def test_nnz_overflow(): ...

class TestInt32Overflow:
    n: int
    def setup_method(self): ...
    def teardown_method(self): ...
    def test_coo_todense(self): ...
    def test_matvecs(self): ...
    def test_dia_matvec(self): ...
    def test_bsr_1_block(self, op) -> Untyped: ...
    def test_bsr_n_block(self, op) -> Untyped: ...

def test_csr_matmat_int64_overflow(): ...
def test_upcast(): ...
def test_endianness(): ...
