from scipy._typing import Untyped

sparray_types: Untyped
sparray_classes: Untyped
A: Untyped
B: Untyped
X: Untyped
sparrays: Untyped
square_sparrays: Untyped
eig_sparrays: Untyped
parametrize_sparrays: Untyped
parametrize_square_sparrays: Untyped
parametrize_eig_sparrays: Untyped

def test_sum(A): ...
def test_mean(A): ...
def test_min_max(A): ...
def test_todense(A): ...
def test_indexing(A): ...
def test_dense_addition(A): ...
def test_sparse_addition(A): ...
def test_elementwise_mul(A): ...
def test_elementwise_rmul(A): ...
def test_matmul(A): ...
def test_power_operator(A): ...
def test_sparse_divide(A): ...
def test_sparse_dense_divide(A): ...
def test_dense_divide(A): ...
def test_no_A_attr(A): ...
def test_no_H_attr(A): ...
def test_getrow_getcol(A): ...
def test_as_linearoperator(A): ...
def test_inv(B): ...
def test_expm(B): ...
def test_expm_multiply(B): ...
def test_norm(A): ...
def test_onenormest(B): ...
def test_spsolve(B): ...
def test_spsolve_triangular(fmt): ...
def test_factorized(B): ...
def test_solvers(B, solver): ...
def test_lstsqr(A, solver): ...
def test_eigs(X): ...
def test_eigsh(X): ...
def test_svds(X): ...
def test_splu(): ...
def test_spilu(): ...
def test_index_dtype_compressed(cls, indices_attrs, expected_dtype): ...
def test_default_is_matrix_diags(): ...
def test_default_is_matrix_eye(): ...
def test_default_is_matrix_spdiags(): ...
def test_default_is_matrix_identity(): ...
def test_default_is_matrix_kron_dense(): ...
def test_default_is_matrix_kron_sparse(): ...
def test_default_is_matrix_kronsum(): ...
def test_default_is_matrix_random(): ...
def test_default_is_matrix_rand(): ...
def test_default_is_matrix_stacks(fn): ...
def test_blocks_default_construction_fn_matrices(): ...
def test_format_property(): ...
def test_issparse(): ...
def test_isspmatrix(): ...
def test_isspmatrix_format(fmt, fn): ...
