# TODO
from scipy._typing import Untyped

__all__ = ["NegativeCycleError", "bellman_ford", "dijkstra", "floyd_warshall", "johnson", "shortest_path", "yen"]

class NegativeCycleError(Exception): ...

def bellman_ford(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def dijkstra(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def floyd_warshall(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def johnson(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def shortest_path(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def yen(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
