# TODO
from scipy._typing import Untyped

__all__ = [
    "construct_dist_matrix",
    "csgraph_from_dense",
    "csgraph_from_masked",
    "csgraph_masked_from_dense",
    "csgraph_to_dense",
    "csgraph_to_masked",
    "reconstruct_path",
]

def construct_dist_matrix(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def csgraph_from_dense(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def csgraph_from_masked(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def csgraph_masked_from_dense(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def csgraph_to_dense(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def csgraph_to_masked(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def reconstruct_path(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
