# TODO
from scipy._typing import Untyped

__all__ = ["breadth_first_order", "breadth_first_tree", "connected_components", "depth_first_order", "depth_first_tree"]

def breadth_first_order(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def breadth_first_tree(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def connected_components(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def depth_first_order(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
def depth_first_tree(*args: Untyped, **kwargs: Untyped) -> Untyped: ...
