# This file is generated by SciPy's build process
# It contains system_info results at the time of building this package.
from enum import Enum
from types import ModuleType
from typing import Final, Literal, TypedDict, overload

__all__ = ["show"]

_ConfigDict = TypedDict(
    "_ConfigDict",
    {
        "Compilers": dict[str, dict[str, str]],
        "Machine Information": dict[str, dict[str, str] | bool],
        "Build Dependencies": dict[str, dict[str, str | bool]],
        "Python Information": dict[str, str],
    },
)

_built_with_meson: Final[bool]

class DisplayModes(Enum):
    stdout = "stdout"
    dicts = "dicts"

CONFIG: Final[_ConfigDict]

def _check_pyyaml() -> ModuleType: ...
@overload
def show(mode: Literal["stdout"] = "stdout") -> _ConfigDict: ...
@overload
def show(mode: Literal["dicts"]) -> _ConfigDict: ...
