from typing import Final
from typing_extensions import LiteralString

short_version: Final[LiteralString] = ...
version: Final[LiteralString] = ...
full_version: Final[LiteralString] = ...
git_revision: Final[LiteralString] = ...
commit_count: Final[LiteralString] = ...
release: Final[bool] = ...
