from typing import Final as _Final
from typing_extensions import LiteralString as _LiteralString

version: _Final[_LiteralString] = ...
full_version: _Final[_LiteralString] = ...
short_version: _Final = "1.15.1"
git_revision: _Final[_LiteralString] = ...
release: _Final[bool] = ...
