generated_code_marker: "@generated"
formatter:
  ["poetry", "run", "ruff", "format", "--stdin-filename=__generated__.pyi", "-"]
blacklist_patterns: []
modules: ["libcst.codemod.commands", "codegen.mods"]
repo_root: "."
