from scipy._typing import Untyped

def linear(r) -> Untyped: ...
def thin_plate_spline(r) -> Untyped: ...
def cubic(r) -> Untyped: ...
def quintic(r) -> Untyped: ...
def multiquadric(r) -> Untyped: ...
def inverse_multiquadric(r) -> Untyped: ...
def inverse_quadratic(r) -> Untyped: ...
def gaussian(r) -> Untyped: ...

NAME_TO_FUNC: Untyped

def kernel_vector(x, y, kernel_func, out): ...
def polynomial_vector(x, powers, out): ...
def kernel_matrix(x, kernel_func, out): ...
def polynomial_matrix(x, powers, out): ...
