# This module is not meant for public use and will be removed in SciPy v2.0.0.
from typing_extensions import deprecated

__all__ = [
    "BarycentricInterpolator",
    "KroghInterpolator",
    "approximate_taylor_polynomial",
    "barycentric_interpolate",
    "krogh_interpolate",
]

@deprecated("will be removed in SciPy v2.0.0")
class KroghInterpolator:
    def __init__(self: object, xi: object, yi: object, axis: object = ...) -> None: ...

@deprecated("will be removed in SciPy v2.0.0")
class BarycentricInterpolator:
    def __init__(
        self: object, xi: object, yi: object = ..., axis: object = ..., *, wi: object = ..., random_state: object = ...
    ) -> None: ...
    def __call__(self: object, x: object) -> object: ...
    def set_yi(self: object, yi: object, axis: object = ...) -> None: ...
    def add_xi(self: object, xi: object, yi: object = ...) -> None: ...
    def derivative(self: object, x: object, der: object = ...) -> object: ...

@deprecated("will be removed in SciPy v2.0.0")
def krogh_interpolate(xi: object, yi: object, x: object, der: object = ..., axis: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def approximate_taylor_polynomial(f: object, x: object, degree: object, scale: object, order: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def barycentric_interpolate(xi: object, yi: object, x: object, axis: object = ..., *, der: object = ...) -> object: ...
