from scipy._typing import Untyped

__all__: list[str] = []

__docformat__: str = ...

def coerce(x: Untyped, y: Untyped) -> Untyped: ...
def id(x: Untyped) -> Untyped: ...
def make_system(A: Untyped, M: Untyped, x0: Untyped, b: Untyped) -> Untyped: ...
