from scipy._typing import Untyped
from scipy.sparse._sputils import matrix as matrix

class TestLinearOperator:
    A: Untyped
    B: Untyped
    C: Untyped
    def setup_method(self): ...
    def test_matvec(self) -> Untyped: ...
    def test_matmul(self) -> Untyped: ...

class TestAsLinearOperator:
    cases: Untyped
    dtype: Untyped
    shape: Untyped
    def setup_method(self) -> Untyped: ...
    def test_basic(self): ...
    def test_dot(self): ...

def test_repr() -> Untyped: ...
def test_identity(): ...
def test_attributes() -> Untyped: ...
def matvec(x) -> Untyped: ...
def test_pickle(): ...
def test_inheritance() -> Untyped: ...
def test_dtypes_of_operator_sum(): ...
def test_no_double_init() -> Untyped: ...
def test_adjoint_conjugate(): ...
def test_ndim(): ...
def test_transpose_noconjugate(): ...
def test_sparse_matmat_exception() -> Untyped: ...
