from scipy._typing import Untyped

def test_sparray_norm(): ...

class TestNorm:
    b: Untyped
    def setup_method(self): ...
    def test_matrix_norm(self): ...
    def test_matrix_norm_axis(self): ...
    def test_vector_norm(self): ...
    def test_norm_exceptions(self): ...

class TestVsNumpyNorm:
    def test_sparse_matrix_norms(self): ...
    def test_sparse_matrix_norms_with_axis(self): ...
    def test_sparse_vector_norms(self): ...
