from scipy._typing import Untyped

pytestmark: Untyped
msg: str
sparse_params: Untyped
scipy_sparse_classes: Untyped

def sparse_cls(request) -> Untyped: ...
def sp_sparse_cls(request) -> Untyped: ...
def same_matrix(sparse_cls, sp_sparse_cls) -> Untyped: ...
def matrices(sparse_cls) -> Untyped: ...
def test_isolve_gmres(matrices): ...
def test_lsmr(matrices): ...
def test_lsmr_output_shape(): ...
def test_lsqr(matrices): ...
def test_eigs(matrices): ...
def test_svds(matrices): ...
def test_lobpcg(matrices): ...
def test_spsolve(matrices): ...
def test_splu(matrices): ...
def test_spilu(matrices): ...
def test_spsolve_triangular(matrices): ...
def test_onenormest(matrices): ...
def test_norm(matrices): ...
def test_inv(matrices): ...
def test_expm(matrices): ...
def test_expm_multiply(matrices): ...
def test_eq(same_matrix): ...
def test_ne(same_matrix): ...
