import scipy.sparse.linalg
from scipy._typing import Untyped

class MatrixProductOperator(scipy.sparse.linalg.LinearOperator):
    A: Untyped
    B: Untyped
    ndim: int
    shape: Untyped
    def __init__(self, A, B) -> None: ...
    @property
    def T(self) -> Untyped: ...

class TestOnenormest:
    def test_onenormest_table_3_t_2(self): ...
    def test_onenormest_table_4_t_7(self): ...
    def test_onenormest_table_5_t_1(self): ...
    def test_onenormest_table_6_t_1(self): ...
    def test_onenormest_linear_operator(self): ...
    def test_returns(self): ...

class TestAlgorithm_2_2:
    def test_randn_inv(self): ...
