from scipy._typing import Untyped
from scipy.sparse import csc_matrix as csc_matrix, csr_matrix as csr_matrix

TOLS: Untyped

def is_complex_type(dtype) -> Untyped: ...

marks: Untyped

def generate_matrix(constructor, n, m, f, dtype=..., rseed: int = 0, **kwargs) -> Untyped: ...
def assert_orthogonal(u1, u2, rtol, atol): ...
def check_svdp(n, m, constructor, dtype, k, irl_mode, which, f: float = 0.8): ...
def test_svdp(ctor, dtype, irl, which): ...
def test_examples(dtype, irl): ...
def test_shifts(shifts, dtype): ...
def test_shifts_accuracy(): ...
