from scipy._typing import Untyped

def axis_slice(
    a, start: Untyped | None = None, stop: Untyped | None = None, step: Untyped | None = None, axis: int = -1
) -> Untyped: ...
def axis_reverse(a, axis: int = -1) -> Untyped: ...
def odd_ext(x, n, axis: int = -1) -> Untyped: ...
def even_ext(x, n, axis: int = -1) -> Untyped: ...
def const_ext(x, n, axis: int = -1) -> Untyped: ...
def zero_ext(x, n, axis: int = -1) -> Untyped: ...
