from typing import TypeAlias

import numpy as np
import optype.numpy as onp
from scipy._typing import Untyped

_Array_fc: TypeAlias = onp.ArrayND[np.float32 | np.float64 | np.complex64 | np.complex128]

def qspline2d(signal: Untyped, lamb: float = 0.0, precision: float = -1.0) -> Untyped: ...
def cspline2d(signal: Untyped, lamb: float = 0.0, precision: float = -1.0) -> Untyped: ...
def sepfir2d(input: _Array_fc, hrow: _Array_fc, hcol: _Array_fc) -> _Array_fc: ...
def symiirorder1(signal: Untyped, c0: Untyped, z1: Untyped, precision: float = -1.0) -> Untyped: ...
def symiirorder2(input: Untyped, r: Untyped, omega: Untyped, precision: float = -1.0) -> Untyped: ...
