from ._upfirdn_apply import mode_enum as mode_enum
from scipy._typing import Untyped

class _UpFIRDn:
    def __init__(self, h, x_dtype, up, down) -> None: ...
    def apply_filter(self, x, axis: int = -1, mode: str = "constant", cval: int = 0) -> Untyped: ...

def upfirdn(h, x, up: int = 1, down: int = 1, axis: int = -1, mode: str = "constant", cval: int = 0) -> Untyped: ...
