from scipy._typing import Untyped

def sawtooth(t, width: int = 1) -> Untyped: ...
def square(t, duty: float = 0.5) -> Untyped: ...
def gausspulse(
    t, fc: int = 1000, bw: float = 0.5, bwr: int = -6, tpr: int = -60, retquad: bool = False, retenv: bool = False
) -> Untyped: ...
def chirp(t, f0, t1, f1, method: str = "linear", phi: int = 0, vertex_zero: bool = True) -> Untyped: ...
def sweep_poly(t, poly, phi: int = 0) -> Untyped: ...
def unit_impulse(shape, idx: Untyped | None = None, dtype=...) -> Untyped: ...
