# This module is not meant for public use and will be removed in SciPy v1.15.0.
from typing_extensions import deprecated

__all__ = ["cascade", "convolve", "cwt", "daub", "morlet", "morlet2", "qmf", "ricker"]

@deprecated("will be removed in SciPy v1.15.0")
def convolve(in1: object, in2: object, mode: object = ..., method: object = ...) -> object: ...
@deprecated("will be removed in SciPy v1.15.0")
def cwt(data: object, wavelet: object, widths: object, dtype: object = ..., **kwargs: object) -> object: ...
@deprecated("will be removed in SciPy v1.15.0")
def cascade(hk: object, J: object = ...) -> object: ...
@deprecated("will be removed in SciPy v1.15.0")
def morlet(M: object, w: object = ..., s: object = ..., complete: object = ...) -> object: ...
@deprecated("will be removed in SciPy v1.15.0")
def daub(p: object) -> object: ...
@deprecated("will be removed in SciPy v1.15.0")
def morlet2(M: object, s: object, w: object = ...) -> object: ...
@deprecated("will be removed in SciPy v1.15.0")
def qmf(hk: object) -> object: ...
@deprecated("will be removed in SciPy v1.15.0")
def ricker(points: object, a: object) -> object: ...
