from ._helpers import all_libraries as all_libraries, import_ as import_, wrapped_libraries as wrapped_libraries
from scipy._typing import Untyped

def test_array_namespace(library, api_version, use_compat) -> Untyped: ...
def test_jax_zero_gradient(): ...
def test_array_namespace_errors() -> Untyped: ...
def test_array_namespace_errors_torch() -> Untyped: ...
def test_api_version() -> Untyped: ...
def test_get_namespace(): ...
