from ..utils import get_arrays_tol as get_arrays_tol
from scipy._typing import Untyped
from scipy.linalg import qr as qr

TINY: Untyped
EPS: Untyped

def tangential_byrd_omojokun(grad, hess_prod, xl, xu, delta, debug, **kwargs) -> Untyped: ...
def constrained_tangential_byrd_omojokun(grad, hess_prod, xl, xu, aub, bub, aeq, delta, debug, **kwargs) -> Untyped: ...
def normal_byrd_omojokun(aub, bub, aeq, beq, xl, xu, delta, debug, **kwargs) -> Untyped: ...
def qr_tangential_byrd_omojokun(aub, aeq, free_xl, free_xu, free_ub) -> Untyped: ...
def qr_normal_byrd_omojokun(aub, free_xl, free_xu, free_slack, free_ub) -> Untyped: ...
