from scipy._typing import Untyped

sig_types: Untyped

def get_type(info, arg) -> Untyped: ...
def make_signature(filename) -> Untyped: ...
def get_sig_name(line) -> Untyped: ...
def sigs_from_dir(directory, outfile, manual_wrappers: Untyped | None = None, exclusions: Untyped | None = None): ...

lapack_manual_wrappers: str
blas_exclusions: Untyped
lapack_exclusions: Untyped
