from ._misc import LinAlgError as LinAlgError
from .lapack import get_lapack_funcs as get_lapack_funcs
from scipy._typing import Untyped

def cholesky(a, lower: bool = False, overwrite_a: bool = False, check_finite: bool = True) -> Untyped: ...
def cho_factor(a, lower: bool = False, overwrite_a: bool = False, check_finite: bool = True) -> Untyped: ...
def cho_solve(c_and_lower, b, overwrite_b: bool = False, check_finite: bool = True) -> Untyped: ...
def cholesky_banded(ab, overwrite_ab: bool = False, lower: bool = False, check_finite: bool = True) -> Untyped: ...
def cho_solve_banded(cb_and_lower, b, overwrite_b: bool = False, check_finite: bool = True) -> Untyped: ...
