from scipy._typing import Untyped

def expm_frechet(A, E, method: Untyped | None = None, compute_expm: bool = True, check_finite: bool = True) -> Untyped: ...
def expm_frechet_block_enlarge(A, E) -> Untyped: ...

ell_table_61: Untyped

def expm_frechet_algo_64(A, E) -> Untyped: ...
def vec(M) -> Untyped: ...
def expm_frechet_kronform(A, method: Untyped | None = None, check_finite: bool = True) -> Untyped: ...
def expm_cond(A, check_finite: bool = True) -> Untyped: ...
