import optype.numpy as onp

__all__ = ["pade_UV_calc", "pick_pade_structure"]

def pick_pade_structure(Am: onp.ArrayND) -> tuple[int, int]: ...
def pade_UV_calc(Am: onp.ArrayND, n: int, m: int) -> None: ...
