import numpy as np
import numpy.typing as npt
from scipy.sparse.linalg._interface import LinearOperator

class LogmRankWarning(UserWarning): ...
class LogmExactlySingularWarning(LogmRankWarning): ...
class LogmNearlySingularWarning(LogmRankWarning): ...
class LogmError(np.linalg.LinAlgError): ...
class FractionalMatrixPowerError(np.linalg.LinAlgError): ...

class _MatrixM1PowerOperator(LinearOperator):
    def __init__(self, A: npt.NDArray[np.number[npt.NBitBase]], p: int) -> None: ...
