from ._basic import inv as inv, solve as solve
from ._decomp_schur import rsf2csf as rsf2csf, schur as schur
from ._decomp_svd import svd as svd
from ._expm_frechet import expm_cond as expm_cond, expm_frechet as expm_frechet
from ._matfuncs_expm import pade_UV_calc as pade_UV_calc, pick_pade_structure as pick_pade_structure
from ._matfuncs_sqrtm import sqrtm as sqrtm
from ._misc import norm as norm
from scipy._typing import Untyped
from scipy.linalg import LinAlgError as LinAlgError, bandwidth as bandwidth

eps: Untyped
feps: Untyped

def fractional_matrix_power(A, t) -> Untyped: ...
def logm(A, disp: bool = True) -> Untyped: ...
def expm(A) -> Untyped: ...
def cosm(A) -> Untyped: ...
def sinm(A) -> Untyped: ...
def tanm(A) -> Untyped: ...
def coshm(A) -> Untyped: ...
def sinhm(A) -> Untyped: ...
def tanhm(A) -> Untyped: ...
def funm(A, func, disp: bool = True) -> Untyped: ...
def signm(A, disp: bool = True) -> Untyped: ...
def khatri_rao(a, b) -> Untyped: ...
