from scipy._typing import Untyped

class _FakeMatrix:
    __array_interface__: Untyped
    def __init__(self, data) -> None: ...

class _FakeMatrix2:
    def __init__(self, data) -> None: ...
    def __array__(self, dtype: Untyped | None = None, copy: Untyped | None = None) -> Untyped: ...

def assert_no_overwrite(call, shapes, dtypes: Untyped | None = None): ...
