from scipy._typing import Untyped

def seed(seed: Untyped | None = None): ...
def rand(*shape) -> Untyped: ...
def interp_decomp(A, eps_or_k, rand: bool = True, rng: Untyped | None = None) -> Untyped: ...
def reconstruct_matrix_from_id(B, idx, proj) -> Untyped: ...
def reconstruct_interp_matrix(idx, proj) -> Untyped: ...
def reconstruct_skel_matrix(A, k, idx) -> Untyped: ...
def id_to_svd(B, idx, proj) -> Untyped: ...
def estimate_spectral_norm(A, its: int = 20, rng: Untyped | None = None) -> Untyped: ...
def estimate_spectral_norm_diff(A, B, its: int = 20, rng: Untyped | None = None) -> Untyped: ...
def svd(A, eps_or_k, rand: bool = True, rng: Untyped | None = None) -> Untyped: ...
def estimate_rank(A, eps, rng: Untyped | None = None) -> Untyped: ...
