# mypy: disable-error-code="misc"
# pyright: reportUnannotatedClassAttribute=false

import abc
from collections.abc import Iterator, Sequence
from typing import Any, Final, Generic, Literal, TypeAlias, overload
from typing_extensions import Self, TypeIs, TypeVar

import numpy as np
import numpy.typing as npt
import optype as op
import optype.numpy as onp
import optype.typing as opt
from scipy._typing import Casting, OrderCF, Untyped
from ._bsr import bsr_array, bsr_matrix
from ._coo import coo_array, coo_matrix
from ._csc import csc_array, csc_matrix
from ._csr import csr_array, csr_matrix
from ._dia import dia_array, dia_matrix
from ._dok import dok_array, dok_matrix
from ._lil import lil_array, lil_matrix
from ._matrix import spmatrix as spmatrix
from ._typing import (
    Complex,
    Float,
    Index1D,
    Int,
    Matrix,
    Scalar,
    SPFormat,
    ToDType,
    ToDTypeBool,
    ToDTypeComplex,
    ToDTypeFloat,
    ToDTypeInt,
    ToShape,
    ToShape1D,
    ToShape2D,
)

__all__ = ["SparseEfficiencyWarning", "SparseWarning", "issparse", "isspmatrix", "sparray"]

_T = TypeVar("_T")
_SCT = TypeVar("_SCT", bound=Scalar)
_SCT_co = TypeVar("_SCT_co", bound=Scalar, default=Scalar, covariant=True)
_SCT_fp = TypeVar("_SCT_fp", bound=Float | Complex)
_ShapeT_co = TypeVar("_ShapeT_co", bound=tuple[int] | tuple[int, int], default=tuple[int] | tuple[int, int], covariant=True)

_ArrayT = TypeVar("_ArrayT", bound=onp.ArrayND)

_SP1DT = TypeVar("_SP1DT", bound=_spbase[Any, tuple[int]])
_SP2DT = TypeVar("_SP2DT", bound=_spbase[Any, tuple[int, int]])

_SPBoolT = TypeVar("_SPBoolT", bound=_spbase[np.bool_])

_SPIntInT = TypeVar("_SPIntInT", bound=_spbase[_FromInt])
_SPFloatInT = TypeVar("_SPFloatInT", bound=_spbase[_FromFloat])
_SPComplexInT = TypeVar("_SPComplexInT", bound=_spbase[_FromComplex])

_FromInt: TypeAlias = Int | Float | Complex
_FromFloat: TypeAlias = Float | Complex
_FromComplex: TypeAlias = Complex

_ToInt8: TypeAlias = np.bool_ | np.int8
_ToFloat32: TypeAlias = np.bool_ | Int | np.float32
_ToFloat: TypeAlias = np.bool_ | Int | Float
_ToComplex64: TypeAlias = np.bool_ | Int | Float | np.complex64

_ToSparseFromPy: TypeAlias = Sequence[Sequence[_T]] | Sequence[_T]
_ToSparseFromArrayLike: TypeAlias = onp.CanArrayND[_SCT_co] | _ToSparseFromPy[_SCT_co]

###

MAXPRINT: Final = 50

class SparseWarning(Warning): ...
class SparseFormatWarning(SparseWarning): ...
class SparseEfficiencyWarning(SparseWarning): ...

class _spbase(Generic[_SCT_co, _ShapeT_co]):
    __array_priority__: float = 10.1
    maxprint: Final[int | None]

    @property
    def ndim(self, /) -> Literal[1, 2]: ...
    @property
    def shape(self, /) -> _ShapeT_co: ...
    @property
    def nnz(self, /) -> int: ...
    @property
    def size(self, /) -> int: ...

    # NOTE: At runtime this isn't abstract, but returns `und` instead.
    @property
    @abc.abstractmethod
    def format(self, /) -> SPFormat: ...

    #
    @property
    def T(self, /) -> Self: ...
    @property
    def real(self, /) -> Self: ...
    @property
    def imag(self, /) -> Self: ...

    # NOTE: In `scipy>=1.15.0` the `maxprint` param will become keyword-only.
    @overload  # shape
    def __init__(self: _spbase[np.float64], /, arg1: ToShape, maxprint: int | None = 50) -> None: ...
    @overload  # sparse
    def __init__(self, /, arg1: _spbase[_SCT_co], maxprint: int | None = 50) -> None: ...
    @overload  # dense array-like
    def __init__(self, /, arg1: _ToSparseFromArrayLike[_SCT_co], maxprint: int | None = 50) -> None: ...
    @overload  # dense array-like bool
    def __init__(self: _spbase[np.bool_], /, arg1: _ToSparseFromPy[bool], maxprint: int | None = 50) -> None: ...
    @overload  # dense array-like int
    def __init__(self: _spbase[np.int_], /, arg1: _ToSparseFromPy[opt.JustInt], maxprint: int | None = 50) -> None: ...
    @overload  # dense array-like float
    def __init__(self: _spbase[np.float64], /, arg1: _ToSparseFromPy[opt.Just[float]], maxprint: int | None = 50) -> None: ...
    @overload  # dense array-like cfloat
    def __init__(
        self: _spbase[np.complex128],
        /,
        arg1: _ToSparseFromPy[opt.Just[complex]],
        maxprint: int | None = 50,
    ) -> None: ...
    @overload  # dense array-like real (pyright is wrong here)
    def __init__(  # pyright: ignore[reportOverlappingOverload]
        self: _spbase[np.float64 | np.int_ | np.bool_],
        /,
        arg1: _ToSparseFromPy[float | int],
        maxprint: int | None = 50,
    ) -> None: ...
    @overload  # dense array-like complex (pyright is wrong here)
    def __init__(  # pyright: ignore[reportOverlappingOverload]
        self: _spbase[np.complex128 | np.float64 | np.int_ | np.bool_],
        /,
        arg1: _ToSparseFromPy[complex | float | int],
        maxprint: int | None = 50,
    ) -> None: ...

    #
    def __bool__(self, /) -> bool: ...

    #
    @overload  # 1-d {csr,dok}_array
    def __iter__(self: csr_array[_SCT, tuple[int]] | dok_array[_SCT, tuple[int]], /) -> Iterator[_SCT]: ...
    @overload  # 2-d {csc,csr}_array
    def __iter__(self: csc_array[_SCT] | csr_array[_SCT, tuple[int, int]], /) -> Iterator[csr_array[_SCT, tuple[int]]]: ...
    @overload  # lil_array
    def __iter__(self: lil_array[_SCT], /) -> Iterator[lil_array[_SCT]]: ...
    @overload  # {csc,csr}_matrix
    def __iter__(self: csc_matrix[_SCT] | csr_matrix[_SCT], /) -> Iterator[csr_matrix[_SCT]]: ...
    @overload  # dok_matrix
    def __iter__(self: dok_matrix[_SCT], /) -> Iterator[dok_matrix[_SCT]]: ...
    @overload  # lil_matrix
    def __iter__(self: lil_matrix[_SCT], /) -> Iterator[lil_matrix[_SCT]]: ...

    #
    @overload
    def __lt__(self: _SPBoolT, other: _spbase[_ToFloat] | onp.ToFloat, /) -> _SPBoolT: ...
    @overload
    def __lt__(self: sparray, other: _spbase[_ToFloat] | onp.ToFloat, /) -> csr_array[np.bool_, _ShapeT_co]: ...
    @overload
    def __lt__(self: spmatrix, other: _spbase[_ToFloat], /) -> csr_matrix[np.bool_]: ...
    #
    @overload
    def __gt__(self: _SPBoolT, other: _spbase[_ToFloat] | onp.ToFloat, /) -> _SPBoolT: ...
    @overload
    def __gt__(self: sparray, other: _spbase[_ToFloat] | onp.ToFloat, /) -> csr_array[np.bool_, _ShapeT_co]: ...
    @overload
    def __gt__(self: spmatrix, other: _spbase[_ToFloat], /) -> csr_matrix[np.bool_]: ...
    #
    @overload
    def __le__(self: _SPBoolT, other: _spbase[_ToFloat] | onp.ToFloat, /) -> _SPBoolT: ...
    @overload
    def __le__(self: sparray, other: _spbase[_ToFloat] | onp.ToFloat, /) -> csr_array[np.bool_, _ShapeT_co]: ...
    @overload
    def __le__(self: spmatrix, other: _spbase[_ToFloat], /) -> csr_matrix[np.bool_]: ...
    #
    @overload
    def __ge__(self: _SPBoolT, other: _spbase[_ToFloat] | onp.ToFloat, /) -> _SPBoolT: ...
    @overload
    def __ge__(self: sparray, other: _spbase[_ToFloat] | onp.ToFloat, /) -> csr_array[np.bool_, _ShapeT_co]: ...
    @overload
    def __ge__(self: spmatrix, other: _spbase[_ToFloat], /) -> csr_matrix[np.bool_]: ...

    #
    def __neg__(self, /) -> Self: ...
    def __abs__(self, /) -> Self: ...
    def __round__(self, /, ndigits: int = 0) -> Self: ...

    # NOTE: only `lil_{array,matrix}` supports non-zero scalar addition (but not subtraction), but upcasts bool + 0 to int_
    @overload  # `0` or sparse of same dtype
    def __add__(self, other: Literal[False, 0] | _spbase[_SCT_co], /) -> Self: ...
    @overload  # sparse[-Int], sparse[+Int8]
    def __add__(self: _SPIntInT, other: _spbase[_ToInt8], /) -> _SPIntInT: ...
    @overload  # sparse[-Float], sparse[+Float32]
    def __add__(self: _SPFloatInT, other: _spbase[_ToFloat32], /) -> _SPFloatInT: ...
    @overload  # sparse[-Complex], sparse[+Complex64]
    def __add__(self: _SPComplexInT, other: _spbase[_ToComplex64], /) -> _SPComplexInT: ...
    @overload  # spmatrix[-Int], array[+Int8]
    def __add__(self: spmatrix[_FromInt], other: onp.ArrayND[_ToInt8], /) -> Matrix[_SCT_co]: ...
    @overload  # spmatrix[-Float], array[+Float32]
    def __add__(self: spmatrix[_FromFloat], other: onp.ArrayND[_ToFloat32], /) -> Matrix[_SCT_co]: ...
    @overload  # spmatrix[-Complex], array[+Complex64]
    def __add__(self: spmatrix[_FromComplex], other: onp.ArrayND[_ToComplex64], /) -> Matrix[_SCT_co]: ...
    @overload  # sparse[-Int], array[+Int8]
    def __add__(self: _spbase[_FromInt], other: onp.ArrayND[_ToInt8], /) -> onp.ArrayND[_SCT_co, _ShapeT_co]: ...
    @overload  # sparse[-Float], array[+Float32]
    def __add__(self: _spbase[_FromFloat], other: onp.ArrayND[_ToFloat32], /) -> onp.ArrayND[_SCT_co, _ShapeT_co]: ...
    @overload  # sparse[-Complex], arrau[+Complex64]
    def __add__(self: _spbase[_FromComplex], other: onp.ArrayND[_ToComplex64], /) -> onp.ArrayND[_SCT_co, _ShapeT_co]: ...
    __radd__ = __add__

    #
    def __sub__(self, other: Untyped, /) -> Untyped: ...
    __rsub__ = __sub__
    #
    def __mul__(self, other: Untyped, /) -> Untyped: ...
    __rmul__ = __mul__
    #
    def __matmul__(self, rhs: Untyped, /) -> Untyped: ...
    __rmatmul__ = __matmul__
    #
    def __truediv__(self, rhs: Untyped, /) -> Untyped: ...
    __div__ = __truediv__

    #
    def __pow__(self, rhs: op.CanIndex, /) -> Self: ...

    #
    def dot(self, /, other: Untyped) -> Untyped: ...
    def multiply(self, /, other: Untyped) -> Untyped: ...
    def maximum(self, /, other: Untyped) -> Untyped: ...
    def minimum(self, /, other: Untyped) -> Untyped: ...

    #
    @overload
    def power(self, /, n: op.CanIndex, dtype: ToDType[_SCT_co] | None = None) -> Self: ...
    @overload
    def power(self, /, n: op.CanIndex, dtype: ToDTypeBool) -> _spbase[np.bool_]: ...
    @overload
    def power(self, /, n: op.CanIndex, dtype: ToDTypeInt) -> _spbase[np.int_]: ...
    @overload
    def power(self, /, n: op.CanIndex, dtype: ToDTypeFloat) -> _spbase[np.float64]: ...
    @overload
    def power(self, /, n: op.CanIndex, dtype: ToDTypeComplex) -> _spbase[np.complex128]: ...
    @overload
    def power(self, /, n: op.CanIndex, dtype: ToDType[_SCT]) -> _spbase[_SCT]: ...

    #
    def nonzero(self, /) -> tuple[Index1D, Index1D]: ...
    def count_nonzero(self, /) -> int: ...
    def conjugate(self, /, copy: bool = True) -> Self: ...
    def conj(self, /, copy: bool = True) -> Self: ...
    def transpose(self, /, axes: None = None, copy: bool = False) -> Self: ...

    #
    def diagonal(self, /, k: int = 0) -> onp.Array1D[_SCT_co]: ...  # only if 2-d
    def trace(self, /, offset: int = 0) -> _SCT_co: ...

    #
    def sum(self, /, axis: op.CanIndex | None = None, dtype: Untyped | None = None, out: Untyped | None = None) -> Untyped: ...
    #
    @overload  # out: array
    def mean(self, /, axis: op.CanIndex | None = None, dtype: npt.DTypeLike | None = None, *, out: _ArrayT) -> _ArrayT: ...
    @overload  # axis: None = ..., dtype: <known>  (keyword)
    def mean(self, /, axis: None = None, *, dtype: ToDType[_SCT], out: None = None) -> _SCT: ...
    @overload  # Self[+Int], axis: None = ...
    def mean(self: _spbase[np.bool_ | Int], /, axis: None = None, dtype: None = None, out: None = None) -> np.float64: ...
    @overload  # spmatrix[+Int], axis: index
    def mean(
        self: spmatrix[np.bool_ | Int],
        /,
        axis: op.CanIndex,
        dtype: None = None,
        out: None = None,
    ) -> Matrix[np.float64]: ...
    @overload  # Self[Float | Complex], axis: None = ...
    def mean(self: _spbase[_SCT_fp], /, axis: None = None, dtype: None = None, out: None = None) -> _SCT_fp: ...
    @overload  # spmatrix[Float | Complex], axis: index
    def mean(self: spmatrix[_SCT_fp], /, axis: op.CanIndex, dtype: None = None, out: None = None) -> Matrix[_SCT_fp]: ...
    @overload  # spmatrix, axis: index, dtype: <unknown>
    def mean(self: spmatrix, /, axis: op.CanIndex, dtype: npt.DTypeLike, out: None = None) -> Matrix[Any]: ...
    @overload  # dtype: <unknown>  (keyword)
    def mean(self, /, axis: op.CanIndex | None = None, *, dtype: npt.DTypeLike, out: None = None) -> Any: ...  # noqa: ANN401

    #
    def copy(self, /) -> Self: ...

    #
    @overload
    def reshape(self: _SP1DT, shape: ToShape1D, /, *, order: OrderCF = "C", copy: bool = False) -> _SP1DT: ...
    @overload
    def reshape(self: _SP2DT, shape: ToShape2D, /, *, order: OrderCF = "C", copy: bool = False) -> _SP2DT: ...

    #
    def astype(self, /, dtype: Untyped, casting: Casting = "unsafe", copy: bool = True) -> Untyped: ...

    #
    @overload
    def asformat(self: sparray, /, format: Literal["bsr"], copy: bool = False) -> bsr_array[_SCT_co]: ...
    @overload
    def asformat(self: spmatrix, /, format: Literal["bsr"], copy: bool = False) -> bsr_matrix[_SCT_co]: ...
    @overload
    def asformat(self: sparray, /, format: Literal["coo"], copy: bool = False) -> coo_array[_SCT_co, _ShapeT_co]: ...
    @overload
    def asformat(self: spmatrix, /, format: Literal["coo"], copy: bool = False) -> coo_matrix[_SCT_co]: ...
    @overload
    def asformat(self: sparray, /, format: Literal["csc"], copy: bool = False) -> csc_array[_SCT_co]: ...
    @overload
    def asformat(self: spmatrix, /, format: Literal["csc"], copy: bool = False) -> csc_matrix[_SCT_co]: ...
    @overload
    def asformat(self: sparray, /, format: Literal["csr"], copy: bool = False) -> csr_array[_SCT_co, _ShapeT_co]: ...
    @overload
    def asformat(self: spmatrix, /, format: Literal["csr"], copy: bool = False) -> csr_matrix[_SCT_co]: ...
    @overload
    def asformat(self: sparray, /, format: Literal["dia"], copy: bool = False) -> dia_array[_SCT_co]: ...
    @overload
    def asformat(self: spmatrix, /, format: Literal["dia"], copy: bool = False) -> dia_matrix[_SCT_co]: ...
    @overload
    def asformat(self: sparray, /, format: Literal["dok"], copy: bool = False) -> dok_array[_SCT_co, _ShapeT_co]: ...
    @overload
    def asformat(self: spmatrix, /, format: Literal["dok"], copy: bool = False) -> dok_matrix[_SCT_co]: ...
    @overload
    def asformat(self: sparray, /, format: Literal["lil"], copy: bool = False) -> lil_array[_SCT_co]: ...
    @overload
    def asformat(self: spmatrix, /, format: Literal["lil"], copy: bool = False) -> lil_matrix[_SCT_co]: ...

    #
    @overload  # self: spmatrix, out: None
    def todense(self: spmatrix, /, order: OrderCF | None = None, out: None = None) -> Matrix[_SCT_co]: ...
    @overload  # self: spmatrix, out: array (positional)
    def todense(self: spmatrix, /, order: OrderCF | None, out: onp.ArrayND[_SCT]) -> Matrix[_SCT]: ...
    @overload  # self: spmatrix, out: array (keyword)
    def todense(self: spmatrix, /, order: OrderCF | None = None, *, out: onp.ArrayND[_SCT]) -> Matrix[_SCT]: ...
    @overload  # out: None
    def todense(self, /, order: OrderCF | None = None, out: None = None) -> onp.Array[_ShapeT_co, _SCT_co]: ...
    @overload  # out: array (positional)
    def todense(self, /, order: OrderCF | None, out: _ArrayT) -> _ArrayT: ...
    @overload  # out: array (keyword)
    def todense(self, /, order: OrderCF | None = None, *, out: _ArrayT) -> _ArrayT: ...

    #
    @overload  # out: None
    def toarray(self, /, order: OrderCF | None = None, out: None = None) -> onp.Array2D[_SCT_co]: ...
    @overload  # out: array (positional)
    def toarray(self, /, order: OrderCF | None, out: _ArrayT) -> _ArrayT: ...
    @overload  # out: array  (keyword)
    def toarray(self, /, order: OrderCF | None = None, *, out: _ArrayT) -> _ArrayT: ...

    #
    @overload
    def tobsr(self: sparray, /, blocksize: tuple[int, int] | None = None, copy: bool = False) -> bsr_array[_SCT_co]: ...
    @overload
    def tobsr(self: spmatrix, /, blocksize: tuple[int, int] | None = None, copy: bool = False) -> bsr_matrix[_SCT_co]: ...
    #
    @overload
    def tocoo(self: sparray, /, copy: bool = False) -> coo_array[_SCT_co, _ShapeT_co]: ...
    @overload
    def tocoo(self: spmatrix, /, copy: bool = False) -> coo_matrix[_SCT_co]: ...
    #
    @overload
    def tocsc(self: sparray, /, copy: bool = False) -> csc_array[_SCT_co]: ...
    @overload
    def tocsc(self: spmatrix, /, copy: bool = False) -> csc_matrix[_SCT_co]: ...
    #
    @overload
    def tocsr(self: sparray, /, copy: bool = False) -> csr_array[_SCT_co, _ShapeT_co]: ...
    @overload
    def tocsr(self: spmatrix, /, copy: bool = False) -> csr_matrix[_SCT_co]: ...
    #
    @overload
    def todia(self: sparray, /, copy: bool = False) -> dia_array[_SCT_co]: ...
    @overload
    def todia(self: spmatrix, /, copy: bool = False) -> dia_matrix[_SCT_co]: ...
    #
    @overload
    def todok(self: sparray, /, copy: bool = False) -> dok_array[_SCT_co, _ShapeT_co]: ...
    @overload
    def todok(self: spmatrix, /, copy: bool = False) -> dok_matrix[_SCT_co]: ...
    #
    @overload
    def tolil(self: sparray, /, copy: bool = False) -> lil_array[_SCT_co]: ...
    @overload
    def tolil(self: spmatrix, /, copy: bool = False) -> lil_matrix[_SCT_co]: ...

    #
    def resize(self, /, shape: ToShape) -> None: ...
    def setdiag(self, /, values: onp.ToComplex1D, k: int = 0) -> None: ...

class sparray: ...

def issparse(x: object) -> TypeIs[_spbase]: ...
def isspmatrix(x: object) -> TypeIs[spmatrix]: ...
