from typing_extensions import override

from scipy._typing import Untyped

from ._base import sparray
from ._compressed import _cs_matrix
from ._matrix import spmatrix

__all__ = ["csr_array", "csr_matrix", "isspmatrix_csr"]

class _csr_base(_cs_matrix):
    @override
    def transpose(self, axes: Untyped | None = None, copy: bool = False) -> Untyped: ...
    @override
    def tolil(self, copy: bool = False) -> Untyped: ...
    @override
    def tocsr(self, copy: bool = False) -> Untyped: ...
    @override
    def tocsc(self, copy: bool = False) -> Untyped: ...
    @override
    def tobsr(self, blocksize: Untyped | None = None, copy: bool = True) -> Untyped: ...
    @override
    def __iter__(self) -> Untyped: ...

class csr_array(_csr_base, sparray): ...
class csr_matrix(spmatrix, _csr_base): ...

def isspmatrix_csr(x: Untyped) -> bool: ...
