from scipy._typing import Untyped

class spmatrix:
    def __mul__(self, other) -> Untyped: ...
    def __rmul__(self, other) -> Untyped: ...
    def __pow__(self, power) -> Untyped: ...
    __dict__: Untyped
    def set_shape(self, shape): ...
    def get_shape(self) -> Untyped: ...
    shape: Untyped
    def asfptype(self) -> Untyped: ...
    def getmaxprint(self) -> Untyped: ...
    def getformat(self) -> Untyped: ...
    def getnnz(self, axis: Untyped | None = None) -> Untyped: ...
    def getH(self) -> Untyped: ...
    def getcol(self, j) -> Untyped: ...
    def getrow(self, i) -> Untyped: ...
    def todense(self, order: Untyped | None = None, out: Untyped | None = None) -> Untyped: ...
