from scipy._typing import Untyped

__all__ = ["spmatrix"]

class spmatrix:
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __mul__(self, other: Untyped, /) -> Untyped: ...
    def __rmul__(self, other: Untyped, /) -> Untyped: ...
    def __pow__(self, power: Untyped, /) -> Untyped: ...
    def set_shape(self, shape: Untyped) -> None: ...
    def get_shape(self) -> tuple[int, ...]: ...
    def asfptype(self) -> Untyped: ...
    def getmaxprint(self) -> Untyped: ...
    def getformat(self) -> Untyped: ...
    def getnnz(self, axis: Untyped | None = None) -> Untyped: ...
    def getH(self) -> Untyped: ...
    def getcol(self, j: int) -> Untyped: ...
    def getrow(self, i: int) -> Untyped: ...
    def todense(self, order: Untyped | None = None, out: Untyped | None = None) -> Untyped: ...
