# This module is not meant for public use and will be removed in SciPy v2.0.0.
from typing_extensions import deprecated

__all__ = [
    "csc_matrix",
    "csc_tocsr",
    "expandptr",
    "isspmatrix_csc",
    "spmatrix",
    "upcast",
]

@deprecated("will be removed in SciPy v2.0.0")
class spmatrix:
    @property
    def shape(self, /) -> tuple[int, ...]: ...
    def __mul__(self, other: object, /) -> object: ...
    def __rmul__(self, other: object, /) -> object: ...
    def __pow__(self, power: object, /) -> object: ...
    def set_shape(self, /, shape: object) -> None: ...
    def get_shape(self, /) -> tuple[int, ...]: ...
    def asfptype(self, /) -> object: ...
    def getmaxprint(self, /) -> object: ...
    def getformat(self, /) -> object: ...
    def getnnz(self, /, axis: object | None = None) -> object: ...
    def getH(self, /) -> object: ...
    def getcol(self, /, j: int) -> object: ...
    def getrow(self, /, i: int) -> object: ...

@deprecated("will be removed in SciPy v2.0.0")
class csc_matrix: ...

@deprecated("will be removed in SciPy v2.0.0")
def isspmatrix_csc(x: object) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def csc_tocsr(*args: object, **kwargs: object) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def expandptr(*args: object, **kwargs: object) -> object: ...

# sputils
@deprecated("will be removed in SciPy v2.0.0")
def upcast(*args: object) -> object: ...
