from scipy._typing import Untyped

def delaunay_plot_2d(tri, ax: Untyped | None = None) -> Untyped: ...
def convex_hull_plot_2d(hull, ax: Untyped | None = None) -> Untyped: ...
def voronoi_plot_2d(vor, ax: Untyped | None = None, **kw) -> Untyped: ...
