from scipy._typing import Untyped
from scipy.spatial import cKDTree as cKDTree

def calculate_solid_angles(R) -> Untyped: ...

class SphericalVoronoi:
    radius: Untyped
    points: Untyped
    center: Untyped
    def __init__(self, points, radius: int = 1, center: Untyped | None = None, threshold: float = 1e-06): ...
    def sort_vertices_of_regions(self): ...
    def calculate_areas(self) -> Untyped: ...
