from scipy._typing import Untyped
from scipy.io.arff import loadarff as loadarff
from scipy.io.arff._arffread import ParseArffError as ParseArffError, read_header as read_header

data_path: Untyped
test1: Untyped
test2: Untyped
test3: Untyped
test4: Untyped
test5: Untyped
test6: Untyped
test7: Untyped
test8: Untyped
test9: Untyped
test10: Untyped
test11: Untyped
test_quoted_nominal: Untyped
test_quoted_nominal_spaces: Untyped
expect4_data: Untyped
expected_types: Untyped
missing: Untyped
expect_missing_raw: Untyped
expect_missing: Untyped

class TestData:
    def test1(self): ...
    def test2(self): ...
    def test3(self): ...
    def test4(self): ...
    def test_filelike(self): ...
    def test_path(self): ...

class TestMissingData:
    def test_missing(self): ...

class TestNoData:
    def test_nodata(self): ...

class TestHeader:
    def test_type_parsing(self): ...
    def test_badtype_parsing(self): ...
    def test_fullheader1(self): ...
    def test_dateheader(self): ...
    def test_dateheader_unsupported(self): ...

class TestDateAttribute:
    def setup_method(self): ...
    def test_year_attribute(self): ...
    def test_month_attribute(self): ...
    def test_date_attribute(self): ...
    def test_datetime_local_attribute(self): ...
    def test_datetime_missing(self): ...
    def test_datetime_timezone(self): ...

class TestRelationalAttribute:
    def setup_method(self): ...
    def test_attributes(self): ...
    def test_data(self): ...

class TestRelationalAttributeLong:
    def setup_method(self): ...
    def test_attributes(self): ...
    def test_data(self): ...

class TestQuotedNominal:
    def setup_method(self): ...
    def test_attributes(self): ...
    def test_data(self): ...

class TestQuotedNominalSpaces:
    def setup_method(self): ...
    def test_attributes(self): ...
    def test_data(self): ...
