from scipy._typing import Untyped
from scipy.integrate import (
    BDF as BDF,
    DOP853 as DOP853,
    LSODA as LSODA,
    RK23 as RK23,
    RK45 as RK45,
    OdeSolution as OdeSolution,
    Radau as Radau,
    solve_ivp as solve_ivp,
)
from scipy.integrate._ivp.base import ConstantDenseOutput as ConstantDenseOutput
from scipy.integrate._ivp.common import num_jac as num_jac, select_initial_step as select_initial_step
from scipy.optimize._numdiff import group_columns as group_columns
from scipy.sparse import coo_matrix as coo_matrix, csc_matrix as csc_matrix

def fun_zero(t, y) -> Untyped: ...
def fun_linear(t, y) -> Untyped: ...
def jac_linear() -> Untyped: ...
def sol_linear(t) -> Untyped: ...
def fun_rational(t, y) -> Untyped: ...
def fun_rational_vectorized(t, y) -> Untyped: ...
def jac_rational(t, y) -> Untyped: ...
def jac_rational_sparse(t, y) -> Untyped: ...
def sol_rational(t) -> Untyped: ...
def fun_medazko(t, y) -> Untyped: ...
def medazko_sparsity(n) -> Untyped: ...
def fun_complex(t, y) -> Untyped: ...
def jac_complex(t, y) -> Untyped: ...
def jac_complex_sparse(t, y) -> Untyped: ...
def sol_complex(t) -> Untyped: ...
def fun_event_dense_output_LSODA(t, y) -> Untyped: ...
def jac_event_dense_output_LSODA(t, y) -> Untyped: ...
def sol_event_dense_output_LSODA(t) -> Untyped: ...
def compute_error(y, y_true, rtol, atol) -> Untyped: ...
def test_integration(): ...
def test_integration_complex(): ...
def test_integration_sparse_difference(): ...
def test_integration_const_jac(): ...
def test_integration_stiff(method) -> Untyped: ...
def test_events() -> Untyped: ...
def test_event_terminal_integer(n_events): ...
def test_event_terminal_iv(): ...
def test_max_step(): ...
def test_first_step(): ...
def test_t_eval(): ...
def test_t_eval_dense_output(): ...
def test_t_eval_early_event() -> Untyped: ...
def test_event_dense_output_LSODA() -> Untyped: ...
def test_no_integration() -> Untyped: ...
def test_no_integration_class() -> Untyped: ...
def test_empty() -> Untyped: ...
def test_ConstantDenseOutput(): ...
def test_classes(): ...
def test_OdeSolution(): ...
def test_num_jac() -> Untyped: ...
def test_num_jac_sparse() -> Untyped: ...
def test_args() -> Untyped: ...
def test_array_rtol() -> Untyped: ...
def test_integration_zero_rhs(method): ...
def test_args_single_value() -> Untyped: ...
def test_initial_state_finiteness(f0_fill): ...
def test_zero_interval(method) -> Untyped: ...
def test_tbound_respected_small_interval(method) -> Untyped: ...
def test_tbound_respected_larger_interval(method) -> Untyped: ...
def test_tbound_respected_oscillator(method) -> Untyped: ...
def test_inital_maxstep(): ...
