from scipy._typing import Untyped
from scipy.integrate import DOP853 as DOP853, RK23 as RK23, RK45 as RK45
from scipy.integrate._ivp import dop853_coefficients as dop853_coefficients

def test_coefficient_properties(solver): ...
def test_coefficient_properties_dop853(): ...
def test_error_estimation(solver_class) -> Untyped: ...
def test_error_estimation_complex(solver_class) -> Untyped: ...
