from typing import Final

from numpy._typing import _ArrayLikeInt_co
from ._odrpack import Model

__all__ = ["Model", "exponential", "multilinear", "polynomial", "quadratic", "unilinear"]

multilinear: Final[_MultilinearModel] = ...
exponential: Final[_ExponentialModel] = ...
unilinear: Final[_UnilinearModel] = ...
quadratic: Final[_QuadraticModel] = ...

class _MultilinearModel(Model):
    def __init__(self, /) -> None: ...

class _ExponentialModel(Model):
    def __init__(self, /) -> None: ...

class _UnilinearModel(Model):
    def __init__(self, /) -> None: ...

class _QuadraticModel(Model):
    def __init__(self, /) -> None: ...

def polynomial(order: _ArrayLikeInt_co) -> Model: ...
