import unittest

from scipy._typing import Untyped

class TestHighsPy(unittest.TestCase):
    def get_basic_model(self) -> Untyped: ...
    def get_infeasible_model(self) -> Untyped: ...
    def test_basics(self): ...
    def test_options(self): ...
    def test_clear(self): ...
    def test_check_solution_feasibility(self): ...
    def test_log_callback(self) -> Untyped: ...
