from scipy._typing import Untyped
from scipy.linalg import norm as norm
from scipy.sparse import csr_matrix as csr_matrix, eye as eye, rand as rand
from scipy.sparse.linalg import splu as splu
from scipy.sparse.linalg._interface import LinearOperator as LinearOperator
from scipy.sparse.linalg._isolve import gmres as gmres, lgmres as lgmres

Am: Untyped
b: Untyped
count: Untyped

def matvec(v) -> Untyped: ...

A: Untyped

def do_solve(**kw) -> Untyped: ...

class TestLGMRES:
    def test_preconditioner(self): ...
    def test_outer_v(self): ...
    def test_arnoldi(self): ...
    def test_cornercase(self): ...
    def test_nans(self): ...
    def test_breakdown_with_outer_v(self): ...
    def test_breakdown_underdetermined(self): ...
    def test_denormals(self): ...
