from ..main import minimize as minimize
from scipy._typing import Untyped
from scipy.optimize import Bounds as Bounds, LinearConstraint as LinearConstraint, NonlinearConstraint as NonlinearConstraint
from scipy.optimize._minimize import standardize_constraints as standardize_constraints

class TestMinimize:
    x0: Untyped
    options: Untyped
    def setup_method(self): ...
    @staticmethod
    def fun(x, c: float = 1.0) -> Untyped: ...
    @staticmethod
    def con(x) -> Untyped: ...
    def test_simple(self): ...
    def test_bounds(self): ...
    def test_minimize_linear_constraints(self): ...
    def test_nonlinear_constraints(self): ...
    def test_minimize_args(self): ...
    n_eval: int
    def test_callback(self): ...
    def test_infeasible_bounds(self): ...
    def test_fixed(self): ...
    def test_target(self): ...
    def test_max_eval(self): ...
    def test_max_iter(self): ...
    def test_feasibility_problem(self): ...
    def test_exceptions(self): ...
    def test_warning(self): ...
