from scipy._typing import Untyped

__all__ = ["expm_multiply"]

def traceest(A, m3, seed: Untyped | None = None) -> Untyped: ...
def expm_multiply(
    A,
    B,
    start: Untyped | None = None,
    stop: Untyped | None = None,
    num: Untyped | None = None,
    endpoint: Untyped | None = None,
    traceA: Untyped | None = None,
) -> Untyped: ...

class LazyOperatorNormInfo:
    def __init__(self, A, A_1_norm: Untyped | None = None, ell: int = 2, scale: int = 1): ...
    def set_scale(self, scale): ...
    def onenorm(self) -> Untyped: ...
    def d(self, p) -> Untyped: ...
    def alpha(self, p) -> Untyped: ...
