from scipy._typing import Untyped

__all__ = ["onenormest"]

def onenormest(A: Untyped, t: int = 2, itmax: int = 5, compute_v: bool = False, compute_w: bool = False) -> Untyped: ...
def sign_round_up(x: Untyped) -> Untyped: ...
def elementary_vector(n: Untyped, i: Untyped) -> Untyped: ...
def vectors_are_parallel(v: Untyped, w: Untyped) -> Untyped: ...
def every_col_of_X_is_parallel_to_a_col_of_Y(X: Untyped, Y: Untyped) -> Untyped: ...
def column_needs_resampling(i: Untyped, X: Untyped, Y: Untyped | None = None) -> Untyped: ...
def resample_column(i: Untyped, X: Untyped) -> None: ...
def less_than_or_close(a: Untyped, b: Untyped) -> Untyped: ...
