from scipy._typing import Untyped

class CensoredData:
    def __init__(
        self,
        uncensored: Untyped | None = None,
        *,
        left: Untyped | None = None,
        right: Untyped | None = None,
        interval: Untyped | None = None,
    ): ...
    def __sub__(self, other) -> Untyped: ...
    def __truediv__(self, other) -> Untyped: ...
    def __len__(self) -> int: ...
    def num_censored(self) -> Untyped: ...
    @classmethod
    def right_censored(cls, x, censored) -> Untyped: ...
    @classmethod
    def left_censored(cls, x, censored) -> Untyped: ...
    @classmethod
    def interval_censored(cls, low, high) -> Untyped: ...
