from scipy._typing import Untyped

def kolmogn(n: Untyped, x: Untyped, cdf: bool = True) -> Untyped: ...
def kolmognp(n: Untyped, x: Untyped) -> Untyped: ...
def kolmogni(n: Untyped, q: Untyped, cdf: bool = True) -> Untyped: ...
