import numpy as np
import numpy.typing as npt
from numpy._typing import _ArrayLikeFloat_co, _ArrayLikeInt
from scipy._typing import AnyBool

def kolmogn(n: _ArrayLikeInt, x: _ArrayLikeFloat_co, cdf: AnyBool = True) -> npt.NDArray[np.float64]: ...
def kolmogni(n: _ArrayLikeInt, q: _ArrayLikeFloat_co, cdf: AnyBool = True) -> npt.NDArray[np.float64]: ...
def kolmognp(n: _ArrayLikeInt, x: _ArrayLikeFloat_co) -> npt.NDArray[np.float64]: ...
