from typing import NamedTuple

from scipy import special as special, stats as stats
from scipy._typing import Untyped

class _MWU:
    def __init__(self, n1, n2) -> None: ...
    n1: Untyped
    n2: Untyped
    s_array: Untyped
    configurations: Untyped
    def set_shapes(self, n1, n2): ...
    def reset(self): ...
    def pmf(self, k) -> Untyped: ...
    def cdf(self, k) -> Untyped: ...
    def sf(self, k) -> Untyped: ...
    def build_sigma_array(self, a) -> Untyped: ...
    def build_u_freqs_array(self, maxu) -> Untyped: ...

class MannwhitneyuResult(NamedTuple):
    statistic: Untyped
    pvalue: Untyped

def mannwhitneyu(
    x, y, use_continuity: bool = True, alternative: str = "two-sided", axis: int = 0, method: str = "auto"
) -> Untyped: ...
