from scipy import stats as stats
from scipy._typing import Untyped

class WilcoxonDistribution:
    n: Untyped
    def __init__(self, n: Untyped) -> None: ...
    def mean(self) -> Untyped: ...
    def cdf(self, k: Untyped) -> Untyped: ...
    def sf(self, k: Untyped) -> Untyped: ...
