from scipy._typing import Untyped

from scipy import stats as stats

class WilcoxonDistribution:
    n: Untyped
    def __init__(self, n) -> None: ...
    def mean(self) -> Untyped: ...
    def cdf(self, k) -> Untyped: ...
    def sf(self, k) -> Untyped: ...
