from scipy.sparse import csr_array as csr_array
from scipy.sparse.csgraph import (
    breadth_first_tree as breadth_first_tree,
    csgraph_from_dense as csgraph_from_dense,
    csgraph_to_dense as csgraph_to_dense,
    depth_first_tree as depth_first_tree,
)

def test_graph_breadth_first(): ...
def test_graph_depth_first(): ...
def test_graph_breadth_first_trivial_graph(): ...
def test_graph_depth_first_trivial_graph(): ...
def test_int64_indices(tree_func, directed): ...
