from scipy import sparse as sparse
from scipy._lib._util import np_long as np_long, np_ulong as np_ulong
from scipy._typing import Untyped
from scipy.sparse import csgraph as csgraph

def check_int_type(mat) -> Untyped: ...
def test_laplacian_value_error(): ...
def test_symmetric_graph_laplacian(): ...

INT_DTYPES: Untyped
REAL_DTYPES: Untyped
COMPLEX_DTYPES: Untyped
DTYPES: Untyped

def test_asymmetric_laplacian(use_out_degree, normed, copy, dtype, arr_type): ...
def test_sparse_formats(fmt, normed, copy): ...
def test_laplacian_symmetrized(arr_type, form): ...
def test_format(dtype, arr_type, normed, symmetrized, use_out_degree, form): ...
def test_format_error_message(): ...
