from scipy._typing import Untyped
from scipy.sparse import csc_matrix as csc_matrix, csr_matrix as csr_matrix
from scipy.sparse.csgraph import maximum_flow as maximum_flow

methods: Untyped

def test_raises_on_dense_input(): ...
def test_raises_on_csc_input(): ...
def test_raises_on_floating_point_input(): ...
def test_raises_on_non_square_input(): ...
def test_raises_when_source_is_sink(): ...
def test_raises_when_source_is_out_of_bounds(source, method): ...
def test_raises_when_sink_is_out_of_bounds(sink, method): ...
def test_simple_graph(method): ...
def test_bottle_neck_graph(method): ...
def test_backwards_flow(method): ...
def test_example_from_clrs_chapter_26_1(method): ...
def test_disconnected_graph(method): ...
def test_add_reverse_edges_large_graph(method): ...
def test_add_reverse_edges(a, b_data_expected): ...
def test_make_edge_pointers(a, expected): ...
def test_make_tails(a, expected): ...
