from ._trustregion import BaseQuadraticSubproblem as BaseQuadraticSubproblem
from scipy._typing import Untyped

class DoglegSubproblem(BaseQuadraticSubproblem):
    def cauchy_point(self) -> Untyped: ...
    def newton_point(self) -> Untyped: ...
    def solve(self, trust_radius) -> Untyped: ...
