from typing import Final

from scipy._typing import Untyped

description: Final[str] = ...

def f1(x: Untyped) -> Untyped: ...
def f1_fp(x: Untyped) -> Untyped: ...
def f1_fpp(x: Untyped) -> Untyped: ...
def f2(x: Untyped) -> Untyped: ...
def f2_fp(x: Untyped) -> Untyped: ...
def f2_fpp(x: Untyped) -> Untyped: ...
def f3(x: Untyped) -> Untyped: ...
def f3_fp(x: Untyped) -> Untyped: ...
def f3_fpp(x: Untyped) -> Untyped: ...
def f4(x: Untyped) -> Untyped: ...
def f5(x: Untyped) -> Untyped: ...
def f6(x: Untyped) -> Untyped: ...
def aps01_f(x: Untyped) -> Untyped: ...
def aps01_fp(x: Untyped) -> Untyped: ...
def aps01_fpp(x: Untyped) -> Untyped: ...
def aps02_f(x: Untyped) -> Untyped: ...
def aps02_fp(x: Untyped) -> Untyped: ...
def aps02_fpp(x: Untyped) -> Untyped: ...
def aps03_f(x: Untyped, a: Untyped, b: Untyped) -> Untyped: ...
def aps03_fp(x: Untyped, a: Untyped, b: Untyped) -> Untyped: ...
def aps03_fpp(x: Untyped, a: Untyped, b: Untyped) -> Untyped: ...
def aps04_f(x: Untyped, n: Untyped, a: Untyped) -> Untyped: ...
def aps04_fp(x: Untyped, n: Untyped, a: Untyped) -> Untyped: ...
def aps04_fpp(x: Untyped, n: Untyped, a: Untyped) -> Untyped: ...
def aps05_f(x: Untyped) -> Untyped: ...
def aps05_fp(x: Untyped) -> Untyped: ...
def aps05_fpp(x: Untyped) -> Untyped: ...
def aps06_f(x: Untyped, n: Untyped) -> Untyped: ...
def aps06_fp(x: Untyped, n: Untyped) -> Untyped: ...
def aps06_fpp(x: Untyped, n: Untyped) -> Untyped: ...
def aps07_f(x: Untyped, n: Untyped) -> Untyped: ...
def aps07_fp(x: Untyped, n: Untyped) -> Untyped: ...
def aps07_fpp(x: Untyped, n: Untyped) -> Untyped: ...
def aps08_f(x: Untyped, n: Untyped) -> Untyped: ...
def aps08_fp(x: Untyped, n: Untyped) -> Untyped: ...
def aps08_fpp(x: Untyped, n: Untyped) -> Untyped: ...
def aps09_f(x: Untyped, n: Untyped) -> Untyped: ...
def aps09_fp(x: Untyped, n: Untyped) -> Untyped: ...
def aps09_fpp(x: Untyped, n: Untyped) -> Untyped: ...
def aps10_f(x: Untyped, n: Untyped) -> Untyped: ...
def aps10_fp(x: Untyped, n: Untyped) -> Untyped: ...
def aps10_fpp(x: Untyped, n: Untyped) -> Untyped: ...
def aps11_f(x: Untyped, n: Untyped) -> Untyped: ...
def aps11_fp(x: Untyped, n: Untyped) -> Untyped: ...
def aps11_fpp(x: Untyped, n: Untyped) -> Untyped: ...
def aps12_f(x: Untyped, n: Untyped) -> Untyped: ...
def aps12_fp(x: Untyped, n: Untyped) -> Untyped: ...
def aps12_fpp(x: Untyped, n: Untyped) -> Untyped: ...
def aps13_f(x: Untyped) -> Untyped: ...
def aps13_fp(x: Untyped) -> Untyped: ...
def aps13_fpp(x: Untyped) -> Untyped: ...
def aps14_f(x: Untyped, n: Untyped) -> Untyped: ...
def aps14_fp(x: Untyped, n: Untyped) -> Untyped: ...
def aps14_fpp(x: Untyped, n: Untyped) -> Untyped: ...
def aps15_f(x: Untyped, n: Untyped) -> Untyped: ...
def aps15_fp(x: Untyped, n: Untyped) -> Untyped: ...
def aps15_fpp(x: Untyped, n: Untyped) -> Untyped: ...
def cplx01_f(z: Untyped, n: Untyped, a: Untyped) -> Untyped: ...
def cplx01_fp(z: Untyped, n: Untyped, a: Untyped) -> Untyped: ...
def cplx01_fpp(z: Untyped, n: Untyped, a: Untyped) -> Untyped: ...
def cplx02_f(z: Untyped, a: Untyped) -> Untyped: ...
def cplx02_fp(z: Untyped, a: Untyped) -> Untyped: ...
def cplx02_fpp(z: Untyped, a: Untyped) -> Untyped: ...
def get_tests(collection: str = "original", smoothness: Untyped | None = None) -> Untyped: ...

methods: Untyped
mstrings: Untyped
functions: Untyped
fstrings: Untyped

def fun1(x: Untyped) -> Untyped: ...
def fun2(x: Untyped) -> Untyped: ...
def fun3(x: Untyped) -> Untyped: ...
def fun4(x: Untyped) -> Untyped: ...
def fun5(x: Untyped) -> Untyped: ...
def fun6(x: Untyped) -> Untyped: ...
def fun7(x: Untyped) -> Untyped: ...
def fun8(x: Untyped) -> Untyped: ...
def fun9(x: Untyped) -> Untyped: ...
