from scipy._lib._array_api import array_namespace as array_namespace
from scipy._typing import Untyped

description: str

def f1(x) -> Untyped: ...
def f1_fp(x) -> Untyped: ...
def f1_fpp(x) -> Untyped: ...
def f2(x) -> Untyped: ...
def f2_fp(x) -> Untyped: ...
def f2_fpp(x) -> Untyped: ...
def f3(x) -> Untyped: ...
def f3_fp(x) -> Untyped: ...
def f3_fpp(x) -> Untyped: ...
def f4(x) -> Untyped: ...
def f5(x) -> Untyped: ...
def f6(x) -> Untyped: ...
def aps01_f(x) -> Untyped: ...
def aps01_fp(x) -> Untyped: ...
def aps01_fpp(x) -> Untyped: ...
def aps02_f(x) -> Untyped: ...
def aps02_fp(x) -> Untyped: ...
def aps02_fpp(x) -> Untyped: ...
def aps03_f(x, a, b) -> Untyped: ...
def aps03_fp(x, a, b) -> Untyped: ...
def aps03_fpp(x, a, b) -> Untyped: ...
def aps04_f(x, n, a) -> Untyped: ...
def aps04_fp(x, n, a) -> Untyped: ...
def aps04_fpp(x, n, a) -> Untyped: ...
def aps05_f(x) -> Untyped: ...
def aps05_fp(x) -> Untyped: ...
def aps05_fpp(x) -> Untyped: ...
def aps06_f(x, n) -> Untyped: ...
def aps06_fp(x, n) -> Untyped: ...
def aps06_fpp(x, n) -> Untyped: ...
def aps07_f(x, n) -> Untyped: ...
def aps07_fp(x, n) -> Untyped: ...
def aps07_fpp(x, n) -> Untyped: ...
def aps08_f(x, n) -> Untyped: ...
def aps08_fp(x, n) -> Untyped: ...
def aps08_fpp(x, n) -> Untyped: ...
def aps09_f(x, n) -> Untyped: ...
def aps09_fp(x, n) -> Untyped: ...
def aps09_fpp(x, n) -> Untyped: ...
def aps10_f(x, n) -> Untyped: ...
def aps10_fp(x, n) -> Untyped: ...
def aps10_fpp(x, n) -> Untyped: ...
def aps11_f(x, n) -> Untyped: ...
def aps11_fp(x, n) -> Untyped: ...
def aps11_fpp(x, n) -> Untyped: ...
def aps12_f(x, n) -> Untyped: ...
def aps12_fp(x, n) -> Untyped: ...
def aps12_fpp(x, n) -> Untyped: ...
def aps13_f(x) -> Untyped: ...
def aps13_fp(x) -> Untyped: ...
def aps13_fpp(x) -> Untyped: ...
def aps14_f(x, n) -> Untyped: ...
def aps14_fp(x, n) -> Untyped: ...
def aps14_fpp(x, n) -> Untyped: ...
def aps15_f(x, n) -> Untyped: ...
def aps15_fp(x, n) -> Untyped: ...
def aps15_fpp(x, n) -> Untyped: ...
def cplx01_f(z, n, a) -> Untyped: ...
def cplx01_fp(z, n, a) -> Untyped: ...
def cplx01_fpp(z, n, a) -> Untyped: ...
def cplx02_f(z, a) -> Untyped: ...
def cplx02_fp(z, a) -> Untyped: ...
def cplx02_fpp(z, a) -> Untyped: ...
def get_tests(collection: str = "original", smoothness: Untyped | None = None) -> Untyped: ...

methods: Untyped
mstrings: Untyped
functions: Untyped
fstrings: Untyped

def fun1(x) -> Untyped: ...
def fun2(x) -> Untyped: ...
def fun3(x) -> Untyped: ...
def fun4(x) -> Untyped: ...
def fun5(x) -> Untyped: ...
def fun6(x) -> Untyped: ...
def fun7(x) -> Untyped: ...
def fun8(x) -> Untyped: ...
def fun9(x) -> Untyped: ...
