from scipy._typing import Untyped
from scipy.io._harwell_boeing._fortran_format_parser import (
    BadFortranFormat as BadFortranFormat,
    ExpFormat as ExpFormat,
    FortranFormatParser as FortranFormatParser,
    IntFormat as IntFormat,
)

class TestFortranFormatParser:
    parser: Untyped
    def setup_method(self): ...
    def test_simple_int(self): ...
    def test_simple_repeated_int(self): ...
    def test_simple_exp(self): ...
    def test_exp_exp(self): ...
    def test_repeat_exp(self): ...
    def test_repeat_exp_exp(self): ...
    def test_wrong_formats(self) -> Untyped: ...

class TestIntFormat:
    def test_to_fortran(self): ...
    def test_from_number(self): ...

class TestExpFormat:
    def test_to_fortran(self): ...
    def test_from_number(self): ...
