from scipy._typing import Untyped

class _ScipyBackend:
    __ua_domain__: str
    @staticmethod
    def __ua_function__(method: Untyped, args: Untyped, kwargs: Untyped) -> Untyped: ...

def set_global_backend(backend: Untyped, coerce: bool = False, only: bool = False, try_last: bool = False) -> None: ...
def register_backend(backend: Untyped) -> None: ...
def set_backend(backend: Untyped, coerce: bool = False, only: bool = False) -> Untyped: ...
def skip_backend(backend: Untyped) -> Untyped: ...
