from scipy._typing import Untyped

__all__ = ["fht", "fhtoffset", "ifht"]

def fht(a, dln, mu, offset: float = 0.0, bias: float = 0.0) -> Untyped: ...
def ifht(A, dln, mu, offset: float = 0.0, bias: float = 0.0) -> Untyped: ...
def fhtcoeff(n, dln, mu, offset: float = 0.0, bias: float = 0.0, inverse: bool = False) -> Untyped: ...
def fhtoffset(dln, mu, initial: float = 0.0, bias: float = 0.0) -> Untyped: ...
