from scipy._typing import Untyped

def next_fast_len(target, real: bool = False): ...
def prev_fast_len(target, real: bool = False): ...
def fftfreq(n, d: float = 1.0, *, xp: Untyped | None = None, device: Untyped | None = None) -> Untyped: ...
def rfftfreq(n, d: float = 1.0, *, xp: Untyped | None = None, device: Untyped | None = None) -> Untyped: ...
def fftshift(x, axes: Untyped | None = None) -> Untyped: ...
def ifftshift(x, axes: Untyped | None = None) -> Untyped: ...
