from scipy._typing import Untyped

def next_fast_len(target: Untyped, real: bool = False) -> None: ...
def prev_fast_len(target: Untyped, real: bool = False) -> None: ...
def fftfreq(n: Untyped, d: float = 1.0, *, xp: Untyped | None = None, device: Untyped | None = None) -> Untyped: ...
def rfftfreq(n: Untyped, d: float = 1.0, *, xp: Untyped | None = None, device: Untyped | None = None) -> Untyped: ...
def fftshift(x: Untyped, axes: Untyped | None = None) -> Untyped: ...
def ifftshift(x: Untyped, axes: Untyped | None = None) -> Untyped: ...
