from scipy._lib._util import normalize_axis_index as normalize_axis_index
from scipy._typing import Untyped

def fourier_gaussian(input, sigma, n: int = -1, axis: int = -1, output: Untyped | None = None) -> Untyped: ...
def fourier_uniform(input, size, n: int = -1, axis: int = -1, output: Untyped | None = None) -> Untyped: ...
def fourier_ellipsoid(input, size, n: int = -1, axis: int = -1, output: Untyped | None = None) -> Untyped: ...
def fourier_shift(input, shift, n: int = -1, axis: int = -1, output: Untyped | None = None) -> Untyped: ...
