from collections.abc import Generator

from scipy._typing import Untyped
from scipy.io.matlab._streams import (
    BLOCK_SIZE as BLOCK_SIZE,
    GenericStream as GenericStream,
    ZlibInputStream as ZlibInputStream,
    make_stream as make_stream,
)

def setup_test_file() -> Generator[Untyped, None, None]: ...
def test_make_stream(): ...
def test_tell_seek(): ...
def test_read(): ...

class TestZlibInputStream:
    def test_read(self): ...
    def test_read_max_length(self): ...
    def test_read_bad_checksum(self): ...
    def test_seek(self): ...
    def test_seek_bad_checksum(self): ...
    def test_all_data_read(self): ...
    def test_all_data_read_overlap(self): ...
    def test_all_data_read_bad_checksum(self): ...
