from scipy._typing import Untyped
from scipy.io.matlab._mio5 import MatFile5Reader as MatFile5Reader

test_data_path: Untyped

def read_minimat_vars(rdr) -> Untyped: ...
def read_workspace_vars(fname) -> Untyped: ...
def test_jottings(): ...
