from scipy._typing import Untyped

def fft(x: Untyped, n: Untyped | None = None, axis: int = -1, overwrite_x: bool = False) -> Untyped: ...
def ifft(x: Untyped, n: Untyped | None = None, axis: int = -1, overwrite_x: bool = False) -> Untyped: ...
def rfft(x: Untyped, n: Untyped | None = None, axis: int = -1, overwrite_x: bool = False) -> Untyped: ...
def irfft(x: Untyped, n: Untyped | None = None, axis: int = -1, overwrite_x: bool = False) -> Untyped: ...
def fftn(x: Untyped, shape: Untyped | None = None, axes: Untyped | None = None, overwrite_x: bool = False) -> Untyped: ...
def ifftn(x: Untyped, shape: Untyped | None = None, axes: Untyped | None = None, overwrite_x: bool = False) -> Untyped: ...
def fft2(x: Untyped, shape: Untyped | None = None, axes: Untyped = (-2, -1), overwrite_x: bool = False) -> Untyped: ...
def ifft2(x: Untyped, shape: Untyped | None = None, axes: Untyped = (-2, -1), overwrite_x: bool = False) -> Untyped: ...
