from scipy._typing import Untyped

__all__ = ["cc_diff", "cs_diff", "diff", "hilbert", "ihilbert", "itilbert", "sc_diff", "shift", "ss_diff", "tilbert"]

def diff(x: Untyped, order: int = 1, period: Untyped | None = None, _cache: Untyped = ...) -> Untyped: ...
def tilbert(x: Untyped, h: Untyped, period: Untyped | None = None, _cache: Untyped = ...) -> Untyped: ...
def itilbert(x: Untyped, h: Untyped, period: Untyped | None = None, _cache: Untyped = ...) -> Untyped: ...
def hilbert(x: Untyped, _cache: Untyped = ...) -> Untyped: ...
def ihilbert(x: Untyped) -> Untyped: ...
def cs_diff(x: Untyped, a: Untyped, b: Untyped, period: Untyped | None = None, _cache: Untyped = ...) -> Untyped: ...
def sc_diff(x: Untyped, a: Untyped, b: Untyped, period: Untyped | None = None, _cache: Untyped = ...) -> Untyped: ...
def ss_diff(x: Untyped, a: Untyped, b: Untyped, period: Untyped | None = None, _cache: Untyped = ...) -> Untyped: ...
def cc_diff(x: Untyped, a: Untyped, b: Untyped, period: Untyped | None = None, _cache: Untyped = ...) -> Untyped: ...
def shift(x: Untyped, a: Untyped, period: Untyped | None = None, _cache: Untyped = ...) -> Untyped: ...
