# This module is not meant for public use and will be removed in SciPy v2.0.0.
from typing_extensions import deprecated

__all__ = ["fft", "fft2", "fftn", "ifft", "ifft2", "ifftn", "irfft", "rfft"]

@deprecated("will be removed in SciPy v2.0.0")
def fft(x: object, n: object = ..., axis: object = ..., overwrite_x: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def ifft(x: object, n: object = ..., axis: object = ..., overwrite_x: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def rfft(x: object, n: object = ..., axis: object = ..., overwrite_x: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def irfft(x: object, n: object = ..., axis: object = ..., overwrite_x: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def fftn(x: object, shape: object = ..., axes: object = ..., overwrite_x: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def ifftn(x: object, shape: object = ..., axes: object = ..., overwrite_x: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def fft2(x: object, shape: object = ..., axes: object = ..., overwrite_x: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def ifft2(x: object, shape: object = ..., axes: object = ..., overwrite_x: object = ...) -> object: ...
