# This module is not meant for public use and will be removed in SciPy v2.0.0.
from typing_extensions import deprecated

from . import convolve as convolve

__all__ = ["cc_diff", "convolve", "cs_diff", "diff", "hilbert", "ihilbert", "itilbert", "sc_diff", "shift", "ss_diff", "tilbert"]

@deprecated("will be removed in SciPy v2.0.0")
def diff(x: object, order: object = 1, period: object = ..., _cache: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def tilbert(x: object, h: object, period: object = ..., _cache: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def itilbert(x: object, h: object, period: object = ..., _cache: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def hilbert(x: object, _cache: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def ihilbert(x: object) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def cs_diff(x: object, a: object, b: object, period: object = ..., _cache: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def sc_diff(x: object, a: object, b: object, period: object = ..., _cache: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def ss_diff(x: object, a: object, b: object, period: object = ..., _cache: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def cc_diff(x: object, a: object, b: object, period: object = ..., _cache: object = ...) -> object: ...
@deprecated("will be removed in SciPy v2.0.0")
def shift(x: object, a: object, period: object = ..., _cache: object = ...) -> object: ...
