from scipy._typing import Untyped
from scipy.optimize._constraints import (
    Bounds as Bounds,
    NonlinearConstraint as NonlinearConstraint,
    PreparedConstraint as PreparedConstraint,
)
from scipy.optimize._trustregion_constr.canonical_constraint import (
    CanonicalConstraint as CanonicalConstraint,
    initial_constraints_as_canonical as initial_constraints_as_canonical,
)

def create_quadratic_function(n, m, rng) -> Untyped: ...
def test_bounds_cases(): ...
def test_nonlinear_constraint(): ...
def test_concatenation(): ...
def test_empty(): ...
def test_initial_constraints_as_canonical(): ...
def test_initial_constraints_as_canonical_empty(): ...
