from numpy.testing import TestCase
from sksparse.cholmod import cholesky_AAt as cholesky_AAt

from scipy._typing import Untyped
from scipy.optimize._trustregion_constr.projections import orthogonality as orthogonality, projections as projections
from scipy.sparse import csc_matrix as csc_matrix

sksparse_available: bool
available_sparse_methods: Untyped
available_dense_methods: Untyped

class TestProjections(TestCase):
    def test_nullspace_and_least_squares_sparse(self): ...
    def test_iterative_refinements_sparse(self): ...
    def test_rowspace_sparse(self): ...
    def test_nullspace_and_least_squares_dense(self): ...
    def test_compare_dense_and_sparse(self): ...
    def test_compare_dense_and_sparse2(self): ...
    def test_iterative_refinements_dense(self): ...
    def test_rowspace_dense(self): ...

class TestOrthogonality(TestCase):
    def test_dense_matrix(self): ...
    def test_sparse_matrix(self): ...
