from ..math import exact_1d_array as exact_1d_array, exact_2d_array as exact_2d_array, get_arrays_tol as get_arrays_tol

class TestGetArraysTol:
    def test_simple(self): ...
    def test_infinite(self): ...
    def test_nan(self): ...
    def test_exceptions(self): ...

class TestExact1DArray:
    def test_simple(self): ...
    def test_broadcast(self): ...
    def test_exceptions(self): ...

class TestExact2DArray:
    def test_simple(self): ...
    def test_broadcast(self): ...
    def test_exceptions(self): ...
