from scipy._typing import Untyped
from scipy.sparse import bmat as bmat, csc_matrix as csc_matrix, eye as eye, issparse as issparse
from scipy.sparse.linalg import LinearOperator as LinearOperator

sksparse_available: bool

def orthogonality(A, g) -> Untyped: ...
def normal_equation_projections(A, m, n, orth_tol, max_refin, tol) -> Untyped: ...
def augmented_system_projections(A, m, n, orth_tol, max_refin, tol) -> Untyped: ...
def qr_factorization_projections(A, m, n, orth_tol, max_refin, tol) -> Untyped: ...
def svd_factorization_projections(A, m, n, orth_tol, max_refin, tol) -> Untyped: ...
def projections(A, method: Untyped | None = None, orth_tol: float = 1e-12, max_refin: int = 3, tol: float = 1e-15) -> Untyped: ...
