from typing import Final

from scipy._typing import Untyped

__all__ = ["orthogonality", "projections"]

sksparse_available: Final[bool] = ...

def orthogonality(A: Untyped, g: Untyped) -> Untyped: ...
def normal_equation_projections(A: Untyped, m: int, n: int, orth_tol: Untyped, max_refin: int, tol: float) -> Untyped: ...
def augmented_system_projections(A: Untyped, m: int, n: int, orth_tol: Untyped, max_refin: int, tol: float) -> Untyped: ...
def qr_factorization_projections(A: Untyped, m: int, n: int, orth_tol: Untyped, max_refin: int, tol: float) -> Untyped: ...
def svd_factorization_projections(A: Untyped, m: int, n: int, orth_tol: Untyped, max_refin: int, tol: float) -> Untyped: ...
def projections(
    A: Untyped,
    method: Untyped | None = None,
    orth_tol: float = 1e-12,
    max_refin: int = 3,
    tol: float = 1e-15,
) -> Untyped: ...
