from scipy._typing import Untyped
from scipy.sparse import bmat as bmat, csc_matrix as csc_matrix, linalg as linalg

def eqp_kktfact(H, c, A, b) -> Untyped: ...
def sphere_intersections(z, d, trust_radius, entire_line: bool = False) -> Untyped: ...
def box_intersections(z, d, lb, ub, entire_line: bool = False) -> Untyped: ...
def box_sphere_intersections(z, d, lb, ub, trust_radius, entire_line: bool = False, extra_info: bool = False) -> Untyped: ...
def inside_box_boundaries(x, lb, ub) -> Untyped: ...
def reinforce_box_boundaries(x, lb, ub) -> Untyped: ...
def modified_dogleg(A, Y, b, trust_radius, lb, ub) -> Untyped: ...
def projected_cg(
    H,
    c,
    Z,
    Y,
    b,
    trust_radius=...,
    lb: Untyped | None = None,
    ub: Untyped | None = None,
    tol: Untyped | None = None,
    max_iter: Untyped | None = None,
    max_infeasible_iter: Untyped | None = None,
    return_all: bool = False,
) -> Untyped: ...
